### ISSUE TITLE
Failed to load nodelet '/EstimatorNodelet` of type `vins_estimator/EstimatorNodelet` to manager `nodelet_manager_pc'

### ISSUE THREAD

**Issue by demul** [jianhengLiu/VINS-RGBD-FAST#3]
[FATAL] [1656675367.836103207]: Failed to load nodelet '/EstimatorNodelet` of type `vins_estimator/EstimatorNodelet` to manager `nodelet_manager_pc'
[nodelet_manager_pc-1] process has died [pid 29090, exit code -11, cmd /opt/ros/melodic/lib/nodelet/nodelet manager __name:=nodelet_manager_pc __log:=/root/.ros/log/47db5b0a-f930-11ec-b3f9-0242ac110003/nodelet_manager_pc-1.log].
log file: /root/.ros/log/47db5b0a-f930-11ec-b3f9-0242ac110003/nodelet_manager_pc-1*.log
[EstimatorNodelet-2] process has died [pid 29091, exit code 255, cmd /opt/ros/melodic/lib/nodelet/nodelet load vins_estimator/EstimatorNodelet nodelet_manager_pc __name:=EstimatorNodelet __log:=/root/.ros/log/47db5b0a-f930-11ec-b3f9-0242ac110003/EstimatorNodelet-2.log].
log file: /root/.ros/log/47db5b0a-f930-11ec-b3f9-0242ac110003/EstimatorNodelet-2*.log

?

**Comment by jianhengLiu** [comment]
i run it fine, try to do another `catkin_make`?
if there any problem feel free to comment

**Comment by demul** [comment]
U can reproduce it

============================

docker run --gpus all -it --name vins_rgbd_fast ros:melodic-ros-core-bionic
apt-get update
apt-get install cmake

# install ceres
apt-get install libgoogle-glog-dev libgflags-dev
apt-get install libatlas-base-dev
apt-get install libeigen3-dev
apt-get install libsuitesparse-dev
wget http://ceres-solver.org/ceres-solver-2.1.0.tar.gz
mkdir ceres-bin
cd ceres-bin/
apt install gcc
apt install g++
cmake ../ceres-solver-2.1.0
make
make install

#Install Sophus
git clone http://github.com/strasdat/Sophus.git
cd Sophus/
git checkout a621ff
mkdir build
cd build
cmake ..
make
make install 

#Install opencv
cd ../..
apt-get install unzip
unzip opencv.zip
mkdir opencv_bin
cd opencv_bin/
cmake ../opencv-4.x/
cmake --build .

# Install ROS Dependencies
cd ../ros_ws
catkin_make
apt-get install ros-cv-bridge
apt-get install ros-melodic-cv-bridge
apt-get install ros-melodic-nodelet
apt-get install ros-melodic-tf
apt-get install ros-melodic-image-transport


#build your Repo
mkdir ros_ws
mkdir ros_ws/src
cd ros_ws/src
git clone https://github.com/jianhengLiu/VINS-RGBD-FAST
cd ..
catkin_make

#Run
roslaunch vins_estimator realsense_vio.launch

# Output
[FATAL] [1656675367.836103207]: Failed to load nodelet '/EstimatorNodeletof typevins_estimator/EstimatorNodeletto managernodelet_manager_pc'
[nodelet_manager_pc-1] process has died [pid 29090, exit code -11, cmd /opt/ros/melodic/lib/nodelet/nodelet manager __name:=nodelet_manager_pc __log:=/root/.ros/log/47db5b0a-f930-11ec-b3f9-0242ac110003/nodelet_manager_pc-1.log].
log file: /root/.ros/log/47db5b0a-f930-11ec-b3f9-0242ac110003/nodelet_manager_pc-1*.log
[EstimatorNodelet-2] process has died [pid 29091, exit code 255, cmd /opt/ros/melodic/lib/nodelet/nodelet load vins_estimator/EstimatorNodelet nodelet_manager_pc __name:=EstimatorNodelet __log:=/root/.ros/log/47db5b0a-f930-11ec-b3f9-0242ac110003/EstimatorNodelet-2.log].
log file: /root/.ros/log/47db5b0a-f930-11ec-b3f9-0242ac110003/EstimatorNodelet-2*.log

==============================================

Please reproduce it and guide me how to resolve it.
or 
Please just share your docker image.

Thanks

**Comment by jianhengLiu** [comment]
it still works fine in the docker.
while i didn't install opencv independently, and used that in ros
i tested it in both ubuntu 20.04 and 18.04

if you have any progress, it will be appreciate to hear

**Comment by demul** [comment]
Could you just share your docker image?
or Guide me how to reproduce it from one of public docker images.

Thanks

**Comment by jianhengLiu** [comment]
> Could you just share your docker image? or Guide me how to reproduce it from one of public docker images.
> 
> Thanks

i just follow your docker instruction while skip the `opencv` part

you could try to use this docker
`docker pull chrisliudocker/vins-rgbd-fast`
i am not much familiar with docker actually, hope it works!

**Comment by demul** [comment]
Thanks! Your Image works!

Using external OpenCV is the cause of nodelet error.

and How about distribute your package with Docker image?
The reproducibility of your Repo will be highly improved.

See this [PR](https://github.com/jianhengLiu/VINS-RGBD-FAST/pull/4).

Thank you for your Contribution.

**Comment by jianhengLiu** [comment]
It is happy to hear that it works and the problem is found.
I have merged your pull request.
Thanks for your contribution!

**Comment by kukulinxin** [comment]
> Thanks! Your Image works!
> 
> Using external OpenCV is the cause of nodelet error.
> 
> and How about distribute your package with Docker image? The reproducibility of your Repo will be highly improved.
> 
> See this [PR](https://github.com/jianhengLiu/VINS-RGBD-FAST/pull/4).
> 
> Thank you for your Contribution.

Hello, I would like to ask what is the reason for the need for opencv that comes with ROS？Thanks！
